### ISSUE TITLE
Move to the bottom of the screen

### ISSUE THREAD

**Issue by albert-ying** [Jean-Tinland/simple-bar-lite#3]
Hi, thank you for developing this!

I noticed sometimes the simple bar uses too many resources (especially when opened for a long time). So I would like to switch to simple bar lite when I'm running something heavy.

I use the `bottom bar` option in simple bar, but I couldn't find similar configuration in the custom JSON file. Is it possible to move the simple bar lite to the bottom so it can occupy the same location?

Thank you!

**Comment by Jean-Tinland** [comment]
Hi! My pleasure, I'm glad it pleases you :)

You can update [this line](
https://github.dev/Jean-Tinland/simple-bar-lite/blob/6d11bcd3e37f6230391e52dba7ab3673d9a7d262/lib/styles/core/base.css#L3) in the `base.css` file: replace the `top` property with `bottom`.

**Comment by albert-ying** [comment]
Thank you!

**Comment by lokxii** [comment]
I changed `top` property to `bottom` and the bar disappeared. Is this method still valid in the newest version of simple-bar-lite?
